language: c
compiler: gcc
env:
  - PATH=$TRAVIS_BUILD_DIR/bin:$PATH MPLCONFIGDIR=$TRAVIS_BUILD_DIR
install:
  - sudo apt-get install python-matplotlib python-numpy python-mpltoolkits.basemap
  # For cross-compiling 32bit binaries (mode=release32)
  - sudo apt-get install libc6-dev-i386
  - bash .travis.sh
script:
  - scons mode=debug
  - scons -c; scons mode=release
  - ./tesstest
  - scons -c; scons mode=release32
  - ./tesstest
  - cd cookbook; make all
notifications:
  email: false
