# Run all the examples and clean up after them
all: simple_tess simple_prism

simple_tess:
	bash simple_tess.sh
	rm output.txt model.txt
	
simple_prism:
	bash simple_prism.sh
	rm output.txt model.txt
